# Chatterbox TTS Custom Component Configuration
# Add this to your Home Assistant configuration.yaml

# Enable the custom component
chatterbox_tts:
  host: 172.30.3.9  # IoT VLAN IP
  port: 8005

# Configure TTS platform to use Chatterbox TTS
tts:
  - platform: chatterbox_tts
    host: 172.30.3.9
    port: 8005
    voice: "Emily"  # Default voice
    temperature: 0.8
    exaggeration: 1.3

# REST commands for direct control (optional - custom component provides services)
rest_command:
  chatterbox_tts_speak:
    url: "http://172.30.3.9:8005/tts"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: >
      {
        "text": "{{ text }}",
        "voice": "{{ voice | default('Emily') }}",
        "temperature": {{ temperature | default(0.8) }},
        "exaggeration": {{ exaggeration | default(1.3) }},
        "speed_factor": {{ speed_factor | default(1.0) }}
      }
    verify_ssl: false
    timeout: 30

  chatterbox_tts_interrupt:
    url: "http://172.30.3.9:8005/interrupt"
    method: POST
    verify_ssl: false
    timeout: 10

# Input controls for UI
input_text:
  chatterbox_says:
    name: "Chatterbox Says"
    max: 500
    initial: ""
    icon: mdi:microphone

input_select:
  chatterbox_voice:
    name: "Chatterbox Voice"
    options:
      - Emily
      - Gianna
      - Thomas
      - Olivia
      - Alexander
      - Cora
      - Gabriel
      - Alice
      - Austin
      - Connor
    initial: Emily
    icon: mdi:account-voice

input_boolean:
  chatterbox_tts_enabled:
    name: "Chatterbox TTS Enabled"
    initial: true
    icon: mdi:account-voice
